[2020-07-30 14:40:05,077] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: jira_datapipeline.fetch_jira_issues 2020-07-30T14:35:00+00:00 [queued]>
[2020-07-30 14:40:05,127] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: jira_datapipeline.fetch_jira_issues 2020-07-30T14:35:00+00:00 [queued]>
[2020-07-30 14:40:05,127] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-07-30 14:40:05,127] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2020-07-30 14:40:05,127] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-07-30 14:40:05,181] {taskinstance.py:887} INFO - Executing <Task(SSHOperator): fetch_jira_issues> on 2020-07-30T14:35:00+00:00
[2020-07-30 14:40:05,198] {standard_task_runner.py:53} INFO - Started process 2477 to run task
[2020-07-30 14:40:05,364] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: jira_datapipeline.fetch_jira_issues 2020-07-30T14:35:00+00:00 [running]> 02f6ef7ded4c
[2020-07-30 14:40:05,437] {ssh_operator.py:91} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2020-07-30 14:40:05,480] {logging_mixin.py:112} INFO - [2020-07-30 14:40:05,478] {base_hook.py:84} INFO - Using connection to: id: hetzner_airflow. Host: 95.217.217.10, Port: 22, Schema: , Login: magalorian, Password: XXXXXXXX, extra: XXXXXXXX
[2020-07-30 14:40:05,481] {logging_mixin.py:112} INFO - [2020-07-30 14:40:05,481] {ssh_hook.py:166} WARNING - Remote Identification Change is not verified. This wont protect against Man-In-The-Middle attacks
[2020-07-30 14:40:05,481] {logging_mixin.py:112} INFO - [2020-07-30 14:40:05,481] {ssh_hook.py:170} WARNING - No Host Key Verification. This wont protect against Man-In-The-Middle attacks
[2020-07-30 14:40:05,493] {logging_mixin.py:112} INFO - [2020-07-30 14:40:05,493] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_7.6p1)
[2020-07-30 14:40:05,573] {taskinstance.py:1128} ERROR - SSH operator error: [Errno 2] No such file or directory: '/usr/local/airflow/.ssh/id_rsa.pub'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/operators/ssh_operator.py", line 108, in execute
    with self.ssh_hook.get_conn() as ssh_client:
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/hooks/ssh_hook.py", line 193, in get_conn
    client.connect(**connect_kwargs)
  File "/usr/local/lib/python3.7/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/usr/local/lib/python3.7/site-packages/paramiko/client.py", line 677, in _auth
    key_filename, pkey_class, passphrase
  File "/usr/local/lib/python3.7/site-packages/paramiko/client.py", line 586, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/usr/local/lib/python3.7/site-packages/paramiko/pkey.py", line 235, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/usr/local/lib/python3.7/site-packages/paramiko/rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/local/lib/python3.7/site-packages/paramiko/rsakey.py", line 175, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
  File "/usr/local/lib/python3.7/site-packages/paramiko/pkey.py", line 307, in _read_private_key_file
    with open(filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/airflow/.ssh/id_rsa.pub'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/operators/ssh_operator.py", line 177, in execute
    raise AirflowException("SSH operator error: {0}".format(str(e)))
airflow.exceptions.AirflowException: SSH operator error: [Errno 2] No such file or directory: '/usr/local/airflow/.ssh/id_rsa.pub'
[2020-07-30 14:40:05,592] {taskinstance.py:1185} INFO - Marking task as FAILED.dag_id=jira_datapipeline, task_id=fetch_jira_issues, execution_date=20200730T143500, start_date=20200730T144005, end_date=20200730T144005
[2020-07-30 14:40:15,003] {logging_mixin.py:112} INFO - [2020-07-30 14:40:15,002] {local_task_job.py:103} INFO - Task exited with return code 1
