[2020-07-30 14:57:06,158] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: test_jira.load_issues 2020-07-30T14:56:00+00:00 [queued]>
[2020-07-30 14:57:06,192] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: test_jira.load_issues 2020-07-30T14:56:00+00:00 [queued]>
[2020-07-30 14:57:06,192] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-07-30 14:57:06,192] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2020-07-30 14:57:06,192] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-07-30 14:57:06,224] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): load_issues> on 2020-07-30T14:56:00+00:00
[2020-07-30 14:57:06,233] {standard_task_runner.py:53} INFO - Started process 14134 to run task
[2020-07-30 14:57:06,376] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: test_jira.load_issues 2020-07-30T14:56:00+00:00 [running]> 02f6ef7ded4c
[2020-07-30 14:57:06,444] {taskinstance.py:1128} ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/jira_datapipeline_dag.py", line 70, in load_issues
    data = json.load(file)
  File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-07-30 14:57:06,448] {taskinstance.py:1185} INFO - Marking task as FAILED.dag_id=test_jira, task_id=load_issues, execution_date=20200730T145600, start_date=20200730T145706, end_date=20200730T145706
[2020-07-30 14:57:16,119] {logging_mixin.py:112} INFO - [2020-07-30 14:57:16,118] {local_task_job.py:103} INFO - Task exited with return code 1
