[2020-07-31 05:47:57,210] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: DAG_jira.load_issues 2020-07-30T20:06:00+00:00 [queued]>
[2020-07-31 05:47:57,238] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: DAG_jira.load_issues 2020-07-30T20:06:00+00:00 [queued]>
[2020-07-31 05:47:57,239] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-07-31 05:47:57,239] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2020-07-31 05:47:57,239] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-07-31 05:47:57,268] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): load_issues> on 2020-07-30T20:06:00+00:00
[2020-07-31 05:47:57,276] {standard_task_runner.py:53} INFO - Started process 1981 to run task
[2020-07-31 05:47:57,412] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: DAG_jira.load_issues 2020-07-30T20:06:00+00:00 [running]> 02f6ef7ded4c
[2020-07-31 05:47:57,469] {taskinstance.py:1128} ERROR - Expecting ',' delimiter: line 1 column 26509 (char 26508)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/KafkaPOC/dags/jira_datapipeline.py", line 69, in load_issues
    data = json.load(file)
  File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 26509 (char 26508)
[2020-07-31 05:47:57,474] {taskinstance.py:1185} INFO - Marking task as FAILED.dag_id=DAG_jira, task_id=load_issues, execution_date=20200730T200600, start_date=20200731T054757, end_date=20200731T054757
[2020-07-31 05:48:07,167] {logging_mixin.py:112} INFO - [2020-07-31 05:48:07,166] {local_task_job.py:103} INFO - Task exited with return code 1
